# fly.toml app configuration file generated for poke-app-apex-client on 2024-08-15T20:32:52-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poke-app-apex-client'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
